#ifndef NEURAL_DEFAULTS_H
#define NEURAL_DEFAULTS_H

#include <stdint.h>

/* Compile-time defaults may be overridden consistently with -DNAME=value. */
#ifndef NEURAL_DEFAULT_TEXT_INITIAL_CAPACITY
#define NEURAL_DEFAULT_TEXT_INITIAL_CAPACITY 256U
#endif

#ifndef NEURAL_DEFAULT_TEXT_MAX_LINE_LENGTH
#define NEURAL_DEFAULT_TEXT_MAX_LINE_LENGTH 65536U
#endif

#ifndef NEURAL_DEFAULT_TOKEN_CAPACITY
#define NEURAL_DEFAULT_TOKEN_CAPACITY 8U
#endif

#ifndef NEURAL_DEFAULT_LAYER_CAPACITY
#define NEURAL_DEFAULT_LAYER_CAPACITY 4U
#endif

#ifndef NEURAL_DEFAULT_SAMPLE_CAPACITY
#define NEURAL_DEFAULT_SAMPLE_CAPACITY 8U
#endif

#ifndef NEURAL_DEFAULT_CAPACITY_GROWTH_FACTOR
#define NEURAL_DEFAULT_CAPACITY_GROWTH_FACTOR 2U
#endif

#ifndef NEURAL_DEFAULT_ERROR_MESSAGE_CAPACITY
#define NEURAL_DEFAULT_ERROR_MESSAGE_CAPACITY 512U
#endif

#ifndef NEURAL_DEFAULT_MODEL_FILENAME
#define NEURAL_DEFAULT_MODEL_FILENAME "model.txt"
#endif

#ifndef NEURAL_DEFAULT_PROJECT_FILENAME
#define NEURAL_DEFAULT_PROJECT_FILENAME "project.conf"
#endif

#ifndef NEURAL_DEFAULT_DATASET_FILENAME
#define NEURAL_DEFAULT_DATASET_FILENAME "train.txt"
#endif

#ifndef NEURAL_DEFAULT_VALIDATION_FILENAME
#define NEURAL_DEFAULT_VALIDATION_FILENAME "validation.txt"
#endif

#ifndef NEURAL_DEFAULT_TEST_FILENAME
#define NEURAL_DEFAULT_TEST_FILENAME "test.txt"
#endif

#ifndef NEURAL_DEFAULT_WEIGHTS_FILENAME
#define NEURAL_DEFAULT_WEIGHTS_FILENAME "weights.txt"
#endif

#ifndef NEURAL_DEFAULT_CHECKPOINT_FILENAME
#define NEURAL_DEFAULT_CHECKPOINT_FILENAME "checkpoint.txt"
#endif

#ifndef NEURAL_DEFAULT_LOCK_FILENAME
#define NEURAL_DEFAULT_LOCK_FILENAME ".neural-c.lock"
#endif

#ifndef NEURAL_DEFAULT_HISTORY_FILENAME
#define NEURAL_DEFAULT_HISTORY_FILENAME "history.txt"
#endif

#ifndef NEURAL_DEFAULT_PREPROCESSING_FILENAME
#define NEURAL_DEFAULT_PREPROCESSING_FILENAME "preprocessing.txt"
#endif

#ifndef NEURAL_DEFAULT_ATOMIC_TEMP_SUFFIX
#define NEURAL_DEFAULT_ATOMIC_TEMP_SUFFIX ".tmp.XXXXXX"
#endif

/* Execution-only default; it is never part of project files or digests. */
#ifndef NEURAL_DEFAULT_THREAD_COUNT
#define NEURAL_DEFAULT_THREAD_COUNT 1U
#endif

#ifndef NEURAL_DEFAULT_REPORT_INTERVAL
#define NEURAL_DEFAULT_REPORT_INTERVAL 0U
#endif

#ifndef NEURAL_DEFAULT_PREDICTION_BATCH_SIZE
#define NEURAL_DEFAULT_PREDICTION_BATCH_SIZE 1024U
#endif

#ifndef NEURAL_DEFAULT_GRADIENT_CHECK_EPSILON
#define NEURAL_DEFAULT_GRADIENT_CHECK_EPSILON 1e-6
#endif

#ifndef NEURAL_DEFAULT_GRADIENT_CHECK_ABSOLUTE_TOLERANCE
#define NEURAL_DEFAULT_GRADIENT_CHECK_ABSOLUTE_TOLERANCE 1e-7
#endif

#ifndef NEURAL_DEFAULT_GRADIENT_CHECK_RELATIVE_TOLERANCE
#define NEURAL_DEFAULT_GRADIENT_CHECK_RELATIVE_TOLERANCE 1e-5
#endif

/* Values materialized by `init`; runtime always reads project.conf. */
#ifndef NEURAL_DEFAULT_INIT_EPOCHS
#define NEURAL_DEFAULT_INIT_EPOCHS 10000U
#endif

#ifndef NEURAL_DEFAULT_INIT_LEARNING_RATE
#define NEURAL_DEFAULT_INIT_LEARNING_RATE 0.5
#endif

#ifndef NEURAL_DEFAULT_INIT_SEED
#define NEURAL_DEFAULT_INIT_SEED UINT64_C(42)
#endif

#ifndef NEURAL_DEFAULT_INIT_LOSS
#define NEURAL_DEFAULT_INIT_LOSS "mse"
#endif

#ifndef NEURAL_DEFAULT_INIT_CHECKPOINT_INTERVAL
#define NEURAL_DEFAULT_INIT_CHECKPOINT_INTERVAL 100U
#endif

#ifndef NEURAL_DEFAULT_INIT_EARLY_STOPPING_PATIENCE
#define NEURAL_DEFAULT_INIT_EARLY_STOPPING_PATIENCE 0U
#endif

#ifndef NEURAL_DEFAULT_INIT_EARLY_STOPPING_MIN_DELTA
#define NEURAL_DEFAULT_INIT_EARLY_STOPPING_MIN_DELTA 0.0
#endif

#ifndef NEURAL_DEFAULT_INIT_BATCH_SIZE
#define NEURAL_DEFAULT_INIT_BATCH_SIZE 0U
#endif

#ifndef NEURAL_DEFAULT_INIT_SHUFFLE
#define NEURAL_DEFAULT_INIT_SHUFFLE 0
#endif

#ifndef NEURAL_DEFAULT_INIT_GRADIENT_CLIP_NORM
#define NEURAL_DEFAULT_INIT_GRADIENT_CLIP_NORM 0.0
#endif

#ifndef NEURAL_DEFAULT_INIT_L1_REGULARIZATION
#define NEURAL_DEFAULT_INIT_L1_REGULARIZATION 0.0
#endif

#ifndef NEURAL_DEFAULT_INIT_L2_REGULARIZATION
#define NEURAL_DEFAULT_INIT_L2_REGULARIZATION 0.0
#endif

#ifndef NEURAL_DEFAULT_INIT_REGULARIZE_BIASES
#define NEURAL_DEFAULT_INIT_REGULARIZE_BIASES 0
#endif

#ifndef NEURAL_DEFAULT_INIT_OPTIMIZER
#define NEURAL_DEFAULT_INIT_OPTIMIZER "gradient_descent"
#endif

#ifndef NEURAL_DEFAULT_INIT_MOMENTUM
#define NEURAL_DEFAULT_INIT_MOMENTUM 0.9
#endif

#ifndef NEURAL_DEFAULT_INIT_ADAM_BETA1
#define NEURAL_DEFAULT_INIT_ADAM_BETA1 0.9
#endif

#ifndef NEURAL_DEFAULT_INIT_ADAM_BETA2
#define NEURAL_DEFAULT_INIT_ADAM_BETA2 0.999
#endif

#ifndef NEURAL_DEFAULT_INIT_ADAM_EPSILON
#define NEURAL_DEFAULT_INIT_ADAM_EPSILON 1e-8
#endif

#ifndef NEURAL_DEFAULT_INIT_LR_SCHEDULE
#define NEURAL_DEFAULT_INIT_LR_SCHEDULE "constant"
#endif

#ifndef NEURAL_DEFAULT_INIT_LR_DECAY
#define NEURAL_DEFAULT_INIT_LR_DECAY 0.5
#endif

#ifndef NEURAL_DEFAULT_INIT_LR_STEP_EPOCHS
#define NEURAL_DEFAULT_INIT_LR_STEP_EPOCHS 100U
#endif

#ifndef NEURAL_DEFAULT_INIT_LR_PLATEAU_PATIENCE
#define NEURAL_DEFAULT_INIT_LR_PLATEAU_PATIENCE 10U
#endif

#ifndef NEURAL_DEFAULT_INIT_LR_PLATEAU_MIN_DELTA
#define NEURAL_DEFAULT_INIT_LR_PLATEAU_MIN_DELTA 0.0
#endif

#ifndef NEURAL_DEFAULT_INIT_DIVERGENCE_THRESHOLD
#define NEURAL_DEFAULT_INIT_DIVERGENCE_THRESHOLD 0.0
#endif

#ifndef NEURAL_DEFAULT_INIT_TARGET_LOSS
#define NEURAL_DEFAULT_INIT_TARGET_LOSS -1.0
#endif

#ifndef NEURAL_DEFAULT_INIT_MAX_NO_IMPROVEMENT_EPOCHS
#define NEURAL_DEFAULT_INIT_MAX_NO_IMPROVEMENT_EPOCHS 0U
#endif

#ifndef NEURAL_DEFAULT_INIT_NO_IMPROVEMENT_MIN_DELTA
#define NEURAL_DEFAULT_INIT_NO_IMPROVEMENT_MIN_DELTA 0.0
#endif

#endif
