#ifndef NEURAL_DEFAULTS_H
#define NEURAL_DEFAULTS_H

#include <stdint.h>

/* Compile-time defaults may be overridden consistently with -DNAME=value. */
#ifndef NEURAL_DEFAULT_TEXT_INITIAL_CAPACITY
#define NEURAL_DEFAULT_TEXT_INITIAL_CAPACITY 256U
#endif

#ifndef NEURAL_DEFAULT_TEXT_MAX_LINE_LENGTH
#define NEURAL_DEFAULT_TEXT_MAX_LINE_LENGTH 65536U
#endif

#ifndef NEURAL_DEFAULT_TOKEN_CAPACITY
#define NEURAL_DEFAULT_TOKEN_CAPACITY 8U
#endif

#ifndef NEURAL_DEFAULT_LAYER_CAPACITY
#define NEURAL_DEFAULT_LAYER_CAPACITY 4U
#endif

#ifndef NEURAL_DEFAULT_SAMPLE_CAPACITY
#define NEURAL_DEFAULT_SAMPLE_CAPACITY 8U
#endif

#ifndef NEURAL_DEFAULT_CAPACITY_GROWTH_FACTOR
#define NEURAL_DEFAULT_CAPACITY_GROWTH_FACTOR 2U
#endif

#ifndef NEURAL_DEFAULT_ERROR_MESSAGE_CAPACITY
#define NEURAL_DEFAULT_ERROR_MESSAGE_CAPACITY 512U
#endif

#ifndef NEURAL_DEFAULT_MODEL_FILENAME
#define NEURAL_DEFAULT_MODEL_FILENAME "model.txt"
#endif

#ifndef NEURAL_DEFAULT_PROJECT_FILENAME
#define NEURAL_DEFAULT_PROJECT_FILENAME "project.conf"
#endif

#ifndef NEURAL_DEFAULT_DATASET_FILENAME
#define NEURAL_DEFAULT_DATASET_FILENAME "train.txt"
#endif

#ifndef NEURAL_DEFAULT_WEIGHTS_FILENAME
#define NEURAL_DEFAULT_WEIGHTS_FILENAME "weights.txt"
#endif

#ifndef NEURAL_DEFAULT_CHECKPOINT_FILENAME
#define NEURAL_DEFAULT_CHECKPOINT_FILENAME "checkpoint.txt"
#endif

#ifndef NEURAL_DEFAULT_ATOMIC_TEMP_SUFFIX
#define NEURAL_DEFAULT_ATOMIC_TEMP_SUFFIX ".tmp.XXXXXX"
#endif

/* Execution-only default; it is never part of project files or digests. */
#ifndef NEURAL_DEFAULT_THREAD_COUNT
#define NEURAL_DEFAULT_THREAD_COUNT 1U
#endif

#ifndef NEURAL_DEFAULT_GRADIENT_CHECK_EPSILON
#define NEURAL_DEFAULT_GRADIENT_CHECK_EPSILON 1e-6
#endif

#ifndef NEURAL_DEFAULT_GRADIENT_CHECK_ABSOLUTE_TOLERANCE
#define NEURAL_DEFAULT_GRADIENT_CHECK_ABSOLUTE_TOLERANCE 1e-7
#endif

#ifndef NEURAL_DEFAULT_GRADIENT_CHECK_RELATIVE_TOLERANCE
#define NEURAL_DEFAULT_GRADIENT_CHECK_RELATIVE_TOLERANCE 1e-5
#endif

/* Values materialized by `init`; runtime always reads project.conf. */
#ifndef NEURAL_DEFAULT_INIT_EPOCHS
#define NEURAL_DEFAULT_INIT_EPOCHS 10000U
#endif

#ifndef NEURAL_DEFAULT_INIT_LEARNING_RATE
#define NEURAL_DEFAULT_INIT_LEARNING_RATE 0.5
#endif

#ifndef NEURAL_DEFAULT_INIT_SEED
#define NEURAL_DEFAULT_INIT_SEED UINT64_C(42)
#endif

#ifndef NEURAL_DEFAULT_INIT_LOSS
#define NEURAL_DEFAULT_INIT_LOSS "mse"
#endif

#ifndef NEURAL_DEFAULT_INIT_CHECKPOINT_INTERVAL
#define NEURAL_DEFAULT_INIT_CHECKPOINT_INTERVAL 100U
#endif

#endif
